# Generated by Django 5.0.6 on 2024-08-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BtrBookmark', '0003_alter_folder_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_children', to='BtrBookmark.folder'),
        ),
    ]
