# Generated by Django 5.0.6 on 2024-08-15 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BtrBookmark', '0004_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_children', to='BtrBookmark.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='folders_accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
