# Generated by Django 5.0.6 on 2024-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BtrBookmark', '0005_alter_folder_parent_folder_alter_folder_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
