# Generated by Django 5.0.6 on 2024-08-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BtrBookmark', '0006_alter_folder_name_alter_link_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
